### ISSUE TITLE
Skipping until the end of a video makes the plugin crash

### ISSUE THREAD

**Issue by fernandopal** [Hiumee/service.discord.richpresence#2]
Basically every time you skip until the end of a video the plugin crashes until is disabled and enabled.

Video following the steps to make the problem appear: https://youtu.be/ekch0VkY1qQ
Log of the crash: https://hastebin.com/elocaqazat.rb

**Comment by Hiumee** [comment]
Was not able to reproduce the crash. I released a new version trying to fix it using the information from the video.
If the problem is not fixed please provide the following information.
+ The problem is with any video or only some of them?
+ Do you use the seek chapter function? (arrow up on keyboard)
+ A new log using the new version

**Comment by fernandopal** [comment]
Well, with the new version It doesn`t even show the "watching menu", when I start playing the video tye plugin crashes like the other time.

- [Error log](https://hastebin.com/ludenarame.rb)
- [Video](https://youtu.be/2gTvtktYB9c)

It happens with every video (at least the 3 that I have played today) and to seek im using an xbox controller, I guess that the joystick does the same as the arrows but in smaller steps.

I have also sent a friend request to you (fernandopal#8193) on discord so I can send more info faster if you want, [my timezone](https://time.is/UTC+2) (I'm usually able to talk from ~12am to ~4am)

**Comment by Hiumee** [comment]
Fixed
